# Generated by Django 2.2 on 2020-08-11 09:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatinvite',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatinvite',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatinvite',
            name='key',
            field=models.UUIDField(default=uuid.UUID('f83cc984-615d-4aab-ba77-5f1151f8d0f6')),
        ),
    ]
