# Generated by Django 2.2 on 2020-08-20 13:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_auto_20200811_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatinvite',
            name='key',
            field=models.UUIDField(default=uuid.UUID('c9de4dda-b6c3-4aaa-a75f-b7c47375c023')),
        ),
    ]
