# Generated by Django 2.2 on 2020-08-20 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_auto_20200820_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatinvite',
            name='key',
            field=models.UUIDField(default=uuid.UUID('504bb506-0e71-445a-a870-ec12eb035ad5')),
        ),
    ]
