# Generated by Django 2.2 on 2020-09-22 10:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_auto_20200820_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatinvite',
            name='key',
            field=models.UUIDField(default=uuid.UUID('f08a033f-1c9f-4a1f-bae7-531b9a6cd260')),
        ),
    ]
