# Generated by Django 2.2 on 2020-08-20 13:04

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20181201_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=fernet_fields.fields.EncryptedTextField(),
        ),
    ]
